/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StorageShow.java
 *
 * Created on 2012-11-9, 20:32:36
 */
package showFrame;

import java.io.File;
import java.util.Vector;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class RoomShow_V2 extends javax.swing.JFrame {

	
	 /**
	 * 
	 */
	private static final long serialVersionUID = 4481870979446630122L;
	public Vector <String> head  ;
	   public Vector<Vector> data;
	   public DefaultTableModel dtm;
		public String roomId;
	
	
    /** Creates new form StorageShow */
    public RoomShow_V2(String roomId) {
    	this.roomId = roomId;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
       private void initComponents() {

    	this.setTitle("1406出入设备显示");
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jb_start = new javax.swing.JButton();
        jb_suspend = new javax.swing.JButton();
        jb_stop = new javax.swing.JButton();
        jlb_state = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 255));

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        head = new Vector<String>();                         //设置表格头
        {head.add("标签号");
        head.add("出/入");
        head.add("通过时间");}
        data = new Vector<Vector>();                         //数据
        dtm = new DefaultTableModel(data,head);              //创建表格的模型
        jTable1 = new javax.swing.JTable(dtm);                    //创建JTable的实例
        jTable1.setRowHeight(40);
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("幼圆", 1, 36));
        jLabel1.setForeground(new java.awt.Color(204, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        //jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/datadisposing/picture/up4.jpg"))); // NOI18N
        String picPath1 = System.getProperty("user.dir")+ File.separator + "picture" + File.separator + "up4.jpg"; 
        Icon icon1 = new ImageIcon(picPath1);
        jLabel1.setIcon(icon1); // NOI18N
        
        jLabel1.setText("1406资产出入显示");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jb_start.setBackground(new java.awt.Color(204, 204, 255));
        //jb_start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/datadisposing/picture/start.jpg"))); // NOI18N
        String picPath2 = System.getProperty("user.dir")+ File.separator + "picture" + File.separator + "start.jpg"; 
        Icon icon2 = new ImageIcon(picPath2);
        jb_start.setIcon(icon2); // NOI18N
        
        jb_start.setBorder(null);
        jb_start.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_startActionPerformed(evt);
            }
        });

        jb_suspend.setBackground(new java.awt.Color(204, 204, 255));
       // jb_suspend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/datadisposing/picture/suspend.jpg"))); // NOI18N
        String picPath3 = System.getProperty("user.dir")+ File.separator + "picture" + File.separator + "suspend.jpg"; 
        Icon icon3 = new ImageIcon(picPath3);
        jb_suspend.setIcon(icon3); // NOI18N
        
        jb_suspend.setBorder(null);
        jb_suspend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_suspendActionPerformed(evt);
            }
        });

        jb_stop.setBackground(new java.awt.Color(204, 204, 255));
        //jb_stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/datadisposing/picture/stop.jpg"))); // NOI18N
        String picPath4 = System.getProperty("user.dir")+ File.separator + "picture" + File.separator + "stop.jpg"; 
        Icon icon4 = new ImageIcon(picPath4);
        jb_stop.setIcon(icon4); // NOI18N
        jb_stop.setBorder(null);
        jb_stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_stopActionPerformed(evt);
            }
        });

        jlb_state.setBackground(new java.awt.Color(204, 204, 255));
        jlb_state.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jlb_state.setForeground(new java.awt.Color(153, 0, 153));
        jlb_state.setText("停止状态");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jb_start, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_suspend, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_stop, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 395, Short.MAX_VALUE)
                .addComponent(jlb_state)
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_start, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_suspend, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_stop, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_state))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold
String state ="stop";
private void jb_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_startActionPerformed
// TODO add your handling code here:

	jlb_state.setText("读取状态");
//	DataDisposing_storage dd = new DataDisposing_storage();
//	dd.readeTxt("d:\\storageInformation.txt");

//	state ="start";
//	while(state.equals("start")){
//		System.out.println("*******");
//		if(state.equals("stop")){break;}
//	}
	
	
	
	
}//GEN-LAST:event_jb_startActionPerformed

private void jb_suspendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_suspendActionPerformed
// TODO add your handling code here:
	jlb_state.setText("暂停状态");
//	while(true){
//		System.out.println("暂停状态*******");
//	}
	
}//GEN-LAST:event_jb_suspendActionPerformed

private void jb_stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_stopActionPerformed
// TODO add your handling code here:
	jlb_state.setText("停止状态");
}//GEN-LAST:event_jb_stopActionPerformed

 


public void updateTable(Vector<String> v){
//	Vector<String> v = new Vector<String>();
//	v.add("11111");v.add("进");v.add("2012-11-09");
	data.add(v);
	dtm.setDataVector(data, head);             		//更新table
	    jTable1.updateUI() ;                    //提示表格已更改
	    jTable1.repaint();  
	
}




    public static void main(String args[]) {
        
    	RoomShow_V2 s=   new RoomShow_V2("1406");
                s.setBounds(100,100,660,700);
                s.setVisible(true);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jb_start;
    private javax.swing.JButton jb_stop;
    private javax.swing.JButton jb_suspend;
    private javax.swing.JLabel jlb_state;
    // End of variables declaration//GEN-END:variables


	public javax.swing.JLabel getJlb_state() {
		return jlb_state;
	}

	public void setJlb_state(javax.swing.JLabel jlbState) {
		jlb_state = jlbState;
	}
}
